### ISSUE TITLE
#UX Feedback + App crashes completely

### ISSUE THREAD

**Issue by Dr4gon** [echo75/graduation-project-johan-hedman#5]
@echo75 Here's the feedback: https://www.loom.com/share/a1f759450fa0454b968c5be795bbd5f4

and the error that crashed the app.

```
graduation-project-johan-hedman-api-1       | /app/node_modules/axios/dist/node/axios.cjs:1909
graduation-project-johan-hedman-api-1       |     reject(new AxiosError(
graduation-project-johan-hedman-api-1       |            ^
graduation-project-johan-hedman-api-1       | 
graduation-project-johan-hedman-api-1       | AxiosError: Request failed with status code 401
graduation-project-johan-hedman-api-1       |     at settle (/app/node_modules/axios/dist/node/axios.cjs:1909:12)
graduation-project-johan-hedman-api-1       |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:2989:11)
graduation-project-johan-hedman-api-1       |     at IncomingMessage.emit (node:events:526:35)
graduation-project-johan-hedman-api-1       |     at endReadableNT (node:internal/streams/readable:1376:12)
graduation-project-johan-hedman-api-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
graduation-project-johan-hedman-api-1       |   code: 'ERR_BAD_REQUEST',
graduation-project-johan-hedman-api-1       |   config: {
graduation-project-johan-hedman-api-1       |     transitional: {
graduation-project-johan-hedman-api-1       |       silentJSONParsing: true,
graduation-project-johan-hedman-api-1       |       forcedJSONParsing: true,
graduation-project-johan-hedman-api-1       |       clarifyTimeoutError: false
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     adapter: [ 'xhr', 'http' ],
graduation-project-johan-hedman-api-1       |     transformRequest: [ [Function: transformRequest] ],
graduation-project-johan-hedman-api-1       |     transformResponse: [ [Function: transformResponse] ],
graduation-project-johan-hedman-api-1       |     timeout: 0,
graduation-project-johan-hedman-api-1       |     xsrfCookieName: 'XSRF-TOKEN',
graduation-project-johan-hedman-api-1       |     xsrfHeaderName: 'X-XSRF-TOKEN',
graduation-project-johan-hedman-api-1       |     maxContentLength: -1,
graduation-project-johan-hedman-api-1       |     maxBodyLength: -1,
graduation-project-johan-hedman-api-1       |     env: {
graduation-project-johan-hedman-api-1       |       FormData: [Function: FormData] {
graduation-project-johan-hedman-api-1       |         LINE_BREAK: '\r\n',
graduation-project-johan-hedman-api-1       |         DEFAULT_CONTENT_TYPE: 'application/octet-stream'
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       Blob: [class Blob]
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     validateStatus: [Function: validateStatus],
graduation-project-johan-hedman-api-1       |     headers: AxiosHeaders {
graduation-project-johan-hedman-api-1       |       Accept: 'application/json, text/plain, */*',
graduation-project-johan-hedman-api-1       |       'User-Agent': 'axios/1.4.0',
graduation-project-johan-hedman-api-1       |       'Accept-Encoding': 'gzip, compress, deflate, br'
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     method: 'get',
graduation-project-johan-hedman-api-1       |     url: 'http://www.omdbapi.com/?apikey=undefined&s=One%20Piece&type=movie',
graduation-project-johan-hedman-api-1       |     data: undefined
graduation-project-johan-hedman-api-1       |   },
graduation-project-johan-hedman-api-1       |   request: <ref *3> ClientRequest {
graduation-project-johan-hedman-api-1       |     _events: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |       abort: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       aborted: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       connect: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       error: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       socket: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       timeout: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |       finish: [Function: requestOnFinish]
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     _eventsCount: 7,
graduation-project-johan-hedman-api-1       |     _maxListeners: undefined,
graduation-project-johan-hedman-api-1       |     outputData: [],
graduation-project-johan-hedman-api-1       |     outputSize: 0,
graduation-project-johan-hedman-api-1       |     writable: true,
graduation-project-johan-hedman-api-1       |     destroyed: true,
graduation-project-johan-hedman-api-1       |     _last: true,
graduation-project-johan-hedman-api-1       |     chunkedEncoding: false,
graduation-project-johan-hedman-api-1       |     shouldKeepAlive: true,
graduation-project-johan-hedman-api-1       |     maxRequestsOnConnectionReached: false,
graduation-project-johan-hedman-api-1       |     _defaultKeepAlive: true,
graduation-project-johan-hedman-api-1       |     useChunkedEncodingByDefault: false,
graduation-project-johan-hedman-api-1       |     sendDate: false,
graduation-project-johan-hedman-api-1       |     _removedConnection: false,
graduation-project-johan-hedman-api-1       |     _removedContLen: false,
graduation-project-johan-hedman-api-1       |     _removedTE: false,
graduation-project-johan-hedman-api-1       |     strictContentLength: false,
graduation-project-johan-hedman-api-1       |     _contentLength: 0,
graduation-project-johan-hedman-api-1       |     _hasBody: true,
graduation-project-johan-hedman-api-1       |     _trailer: '',
graduation-project-johan-hedman-api-1       |     finished: true,
graduation-project-johan-hedman-api-1       |     _headerSent: true,
graduation-project-johan-hedman-api-1       |     _closed: true,
graduation-project-johan-hedman-api-1       |     socket: <ref *1> Socket {
graduation-project-johan-hedman-api-1       |       connecting: false,
graduation-project-johan-hedman-api-1       |       _hadError: false,
graduation-project-johan-hedman-api-1       |       _parent: null,
graduation-project-johan-hedman-api-1       |       _host: 'www.omdbapi.com',
graduation-project-johan-hedman-api-1       |       _closeAfterHandlingError: false,
graduation-project-johan-hedman-api-1       |       _readableState: ReadableState {
graduation-project-johan-hedman-api-1       |         objectMode: false,
graduation-project-johan-hedman-api-1       |         highWaterMark: 16384,
graduation-project-johan-hedman-api-1       |         buffer: BufferList { head: null, tail: null, length: 0 },
graduation-project-johan-hedman-api-1       |         length: 0,
graduation-project-johan-hedman-api-1       |         pipes: [],
graduation-project-johan-hedman-api-1       |         flowing: true,
graduation-project-johan-hedman-api-1       |         ended: false,
graduation-project-johan-hedman-api-1       |         endEmitted: false,
graduation-project-johan-hedman-api-1       |         reading: true,
graduation-project-johan-hedman-api-1       |         constructed: true,
graduation-project-johan-hedman-api-1       |         sync: false,
graduation-project-johan-hedman-api-1       |         needReadable: true,
graduation-project-johan-hedman-api-1       |         emittedReadable: false,
graduation-project-johan-hedman-api-1       |         readableListening: false,
graduation-project-johan-hedman-api-1       |         resumeScheduled: false,
graduation-project-johan-hedman-api-1       |         errorEmitted: false,
graduation-project-johan-hedman-api-1       |         emitClose: false,
graduation-project-johan-hedman-api-1       |         autoDestroy: true,
graduation-project-johan-hedman-api-1       |         destroyed: false,
graduation-project-johan-hedman-api-1       |         errored: null,
graduation-project-johan-hedman-api-1       |         closed: false,
graduation-project-johan-hedman-api-1       |         closeEmitted: false,
graduation-project-johan-hedman-api-1       |         defaultEncoding: 'utf8',
graduation-project-johan-hedman-api-1       |         awaitDrainWriters: null,
graduation-project-johan-hedman-api-1       |         multiAwaitDrain: false,
graduation-project-johan-hedman-api-1       |         readingMore: false,
graduation-project-johan-hedman-api-1       |         dataEmitted: true,
graduation-project-johan-hedman-api-1       |         decoder: null,
graduation-project-johan-hedman-api-1       |         encoding: null,
graduation-project-johan-hedman-api-1       |         [Symbol(kPaused)]: false
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       _events: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |         end: [Function: onReadableStreamEnd],
graduation-project-johan-hedman-api-1       |         free: [Function: onFree],
graduation-project-johan-hedman-api-1       |         close: [Function: onClose],
graduation-project-johan-hedman-api-1       |         timeout: [Function: onTimeout],
graduation-project-johan-hedman-api-1       |         agentRemove: [Function: onRemove],
graduation-project-johan-hedman-api-1       |         error: [Function: bound onceWrapper] {
graduation-project-johan-hedman-api-1       |           listener: [Function: freeSocketErrorListener]
graduation-project-johan-hedman-api-1       |         }
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       _eventsCount: 6,
graduation-project-johan-hedman-api-1       |       _maxListeners: undefined,
graduation-project-johan-hedman-api-1       |       _writableState: WritableState {
graduation-project-johan-hedman-api-1       |         objectMode: false,
graduation-project-johan-hedman-api-1       |         highWaterMark: 16384,
graduation-project-johan-hedman-api-1       |         finalCalled: false,
graduation-project-johan-hedman-api-1       |         needDrain: false,
graduation-project-johan-hedman-api-1       |         ending: false,
graduation-project-johan-hedman-api-1       |         ended: false,
graduation-project-johan-hedman-api-1       |         finished: false,
graduation-project-johan-hedman-api-1       |         destroyed: false,
graduation-project-johan-hedman-api-1       |         decodeStrings: false,
graduation-project-johan-hedman-api-1       |         defaultEncoding: 'utf8',
graduation-project-johan-hedman-api-1       |         length: 0,
graduation-project-johan-hedman-api-1       |         writing: false,
graduation-project-johan-hedman-api-1       |         corked: 0,
graduation-project-johan-hedman-api-1       |         sync: false,
graduation-project-johan-hedman-api-1       |         bufferProcessing: false,
graduation-project-johan-hedman-api-1       |         onwrite: [Function: bound onwrite],
graduation-project-johan-hedman-api-1       |         writecb: null,
graduation-project-johan-hedman-api-1       |         writelen: 0,
graduation-project-johan-hedman-api-1       |         afterWriteTickInfo: null,
graduation-project-johan-hedman-api-1       |         buffered: [],
graduation-project-johan-hedman-api-1       |         bufferedIndex: 0,
graduation-project-johan-hedman-api-1       |         allBuffers: true,
graduation-project-johan-hedman-api-1       |         allNoop: true,
graduation-project-johan-hedman-api-1       |         pendingcb: 0,
graduation-project-johan-hedman-api-1       |         constructed: true,
graduation-project-johan-hedman-api-1       |         prefinished: false,
graduation-project-johan-hedman-api-1       |         errorEmitted: false,
graduation-project-johan-hedman-api-1       |         emitClose: false,
graduation-project-johan-hedman-api-1       |         autoDestroy: true,
graduation-project-johan-hedman-api-1       |         errored: null,
graduation-project-johan-hedman-api-1       |         closed: false,
graduation-project-johan-hedman-api-1       |         closeEmitted: false,
graduation-project-johan-hedman-api-1       |         [Symbol(kOnFinished)]: []
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       allowHalfOpen: false,
graduation-project-johan-hedman-api-1       |       _sockname: null,
graduation-project-johan-hedman-api-1       |       _pendingData: null,
graduation-project-johan-hedman-api-1       |       _pendingEncoding: '',
graduation-project-johan-hedman-api-1       |       server: null,
graduation-project-johan-hedman-api-1       |       _server: null,
graduation-project-johan-hedman-api-1       |       timeout: 5000,
graduation-project-johan-hedman-api-1       |       parser: null,
graduation-project-johan-hedman-api-1       |       _httpMessage: null,
graduation-project-johan-hedman-api-1       |       autoSelectFamilyAttemptedAddresses: [ '172.67.19.55:80' ],
graduation-project-johan-hedman-api-1       |       [Symbol(async_id_symbol)]: -1,
graduation-project-johan-hedman-api-1       |       [Symbol(kHandle)]: TCP {
graduation-project-johan-hedman-api-1       |         reading: true,
graduation-project-johan-hedman-api-1       |         onconnection: null,
graduation-project-johan-hedman-api-1       |         [Symbol(owner_symbol)]: [Circular *1]
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       [Symbol(lastWriteQueueSize)]: 0,
graduation-project-johan-hedman-api-1       |       [Symbol(timeout)]: <ref *2> Timeout {
graduation-project-johan-hedman-api-1       |         _idleTimeout: 5000,
graduation-project-johan-hedman-api-1       |         _idlePrev: TimersList {
graduation-project-johan-hedman-api-1       |           _idleNext: [Circular *2],
graduation-project-johan-hedman-api-1       |           _idlePrev: [Circular *2],
graduation-project-johan-hedman-api-1       |           expiry: 911028,
graduation-project-johan-hedman-api-1       |           id: -9007199254740818,
graduation-project-johan-hedman-api-1       |           msecs: 5000,
graduation-project-johan-hedman-api-1       |           priorityQueuePosition: 1
graduation-project-johan-hedman-api-1       |         },
graduation-project-johan-hedman-api-1       |         _idleNext: TimersList {
graduation-project-johan-hedman-api-1       |           _idleNext: [Circular *2],
graduation-project-johan-hedman-api-1       |           _idlePrev: [Circular *2],
graduation-project-johan-hedman-api-1       |           expiry: 911028,
graduation-project-johan-hedman-api-1       |           id: -9007199254740818,
graduation-project-johan-hedman-api-1       |           msecs: 5000,
graduation-project-johan-hedman-api-1       |           priorityQueuePosition: 1
graduation-project-johan-hedman-api-1       |         },
graduation-project-johan-hedman-api-1       |         _idleStart: 906191,
graduation-project-johan-hedman-api-1       |         _onTimeout: [Function: bound ],
graduation-project-johan-hedman-api-1       |         _timerArgs: undefined,
graduation-project-johan-hedman-api-1       |         _repeat: null,
graduation-project-johan-hedman-api-1       |         _destroyed: false,
graduation-project-johan-hedman-api-1       |         [Symbol(refed)]: false,
graduation-project-johan-hedman-api-1       |         [Symbol(kHasPrimitive)]: false,
graduation-project-johan-hedman-api-1       |         [Symbol(asyncId)]: 1485,
graduation-project-johan-hedman-api-1       |         [Symbol(triggerId)]: 1483
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       [Symbol(kBuffer)]: null,
graduation-project-johan-hedman-api-1       |       [Symbol(kBufferCb)]: null,
graduation-project-johan-hedman-api-1       |       [Symbol(kBufferGen)]: null,
graduation-project-johan-hedman-api-1       |       [Symbol(kCapture)]: false,
graduation-project-johan-hedman-api-1       |       [Symbol(kSetNoDelay)]: true,
graduation-project-johan-hedman-api-1       |       [Symbol(kSetKeepAlive)]: true,
graduation-project-johan-hedman-api-1       |       [Symbol(kSetKeepAliveInitialDelay)]: 1,
graduation-project-johan-hedman-api-1       |       [Symbol(kBytesRead)]: 0,
graduation-project-johan-hedman-api-1       |       [Symbol(kBytesWritten)]: 0
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     _header: 'GET /?apikey=undefined&s=One%20Piece&type=movie HTTP/1.1\r\n' +
graduation-project-johan-hedman-api-1       |       'Accept: application/json, text/plain, */*\r\n' +
graduation-project-johan-hedman-api-1       |       'User-Agent: axios/1.4.0\r\n' +
graduation-project-johan-hedman-api-1       |       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
graduation-project-johan-hedman-api-1       |       'Host: www.omdbapi.com\r\n' +
graduation-project-johan-hedman-api-1       |       'Connection: keep-alive\r\n' +
graduation-project-johan-hedman-api-1       |       '\r\n',
graduation-project-johan-hedman-api-1       |     _keepAliveTimeout: 0,
graduation-project-johan-hedman-api-1       |     _onPendingData: [Function: nop],
graduation-project-johan-hedman-api-1       |     agent: Agent {
graduation-project-johan-hedman-api-1       |       _events: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |         free: [Function (anonymous)],
graduation-project-johan-hedman-api-1       |         newListener: [Function: maybeEnableKeylog]
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       _eventsCount: 2,
graduation-project-johan-hedman-api-1       |       _maxListeners: undefined,
graduation-project-johan-hedman-api-1       |       defaultPort: 80,
graduation-project-johan-hedman-api-1       |       protocol: 'http:',
graduation-project-johan-hedman-api-1       |       options: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |         keepAlive: true,
graduation-project-johan-hedman-api-1       |         scheduling: 'lifo',
graduation-project-johan-hedman-api-1       |         timeout: 5000,
graduation-project-johan-hedman-api-1       |         noDelay: true,
graduation-project-johan-hedman-api-1       |         path: null
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       requests: [Object: null prototype] {},
graduation-project-johan-hedman-api-1       |       sockets: [Object: null prototype] {},
graduation-project-johan-hedman-api-1       |       freeSockets: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |         'www.omdbapi.com:80:': [
graduation-project-johan-hedman-api-1       |           <ref *1> Socket {
graduation-project-johan-hedman-api-1       |             connecting: false,
graduation-project-johan-hedman-api-1       |             _hadError: false,
graduation-project-johan-hedman-api-1       |             _parent: null,
graduation-project-johan-hedman-api-1       |             _host: 'www.omdbapi.com',
graduation-project-johan-hedman-api-1       |             _closeAfterHandlingError: false,
graduation-project-johan-hedman-api-1       |             _readableState: [ReadableState],
graduation-project-johan-hedman-api-1       |             _events: [Object: null prototype],
graduation-project-johan-hedman-api-1       |             _eventsCount: 6,
graduation-project-johan-hedman-api-1       |             _maxListeners: undefined,
graduation-project-johan-hedman-api-1       |             _writableState: [WritableState],
graduation-project-johan-hedman-api-1       |             allowHalfOpen: false,
graduation-project-johan-hedman-api-1       |             _sockname: null,
graduation-project-johan-hedman-api-1       |             _pendingData: null,
graduation-project-johan-hedman-api-1       |             _pendingEncoding: '',
graduation-project-johan-hedman-api-1       |             server: null,
graduation-project-johan-hedman-api-1       |             _server: null,
graduation-project-johan-hedman-api-1       |             timeout: 5000,
graduation-project-johan-hedman-api-1       |             parser: null,
graduation-project-johan-hedman-api-1       |             _httpMessage: null,
graduation-project-johan-hedman-api-1       |             autoSelectFamilyAttemptedAddresses: [Array],
graduation-project-johan-hedman-api-1       |             [Symbol(async_id_symbol)]: -1,
graduation-project-johan-hedman-api-1       |             [Symbol(kHandle)]: [TCP],
graduation-project-johan-hedman-api-1       |             [Symbol(lastWriteQueueSize)]: 0,
graduation-project-johan-hedman-api-1       |             [Symbol(timeout)]: [Timeout],
graduation-project-johan-hedman-api-1       |             [Symbol(kBuffer)]: null,
graduation-project-johan-hedman-api-1       |             [Symbol(kBufferCb)]: null,
graduation-project-johan-hedman-api-1       |             [Symbol(kBufferGen)]: null,
graduation-project-johan-hedman-api-1       |             [Symbol(kCapture)]: false,
graduation-project-johan-hedman-api-1       |             [Symbol(kSetNoDelay)]: true,
graduation-project-johan-hedman-api-1       |             [Symbol(kSetKeepAlive)]: true,
graduation-project-johan-hedman-api-1       |             [Symbol(kSetKeepAliveInitialDelay)]: 1,
graduation-project-johan-hedman-api-1       |             [Symbol(kBytesRead)]: 0,
graduation-project-johan-hedman-api-1       |             [Symbol(kBytesWritten)]: 0
graduation-project-johan-hedman-api-1       |           }
graduation-project-johan-hedman-api-1       |         ]
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       keepAliveMsecs: 1000,
graduation-project-johan-hedman-api-1       |       keepAlive: true,
graduation-project-johan-hedman-api-1       |       maxSockets: Infinity,
graduation-project-johan-hedman-api-1       |       maxFreeSockets: 256,
graduation-project-johan-hedman-api-1       |       scheduling: 'lifo',
graduation-project-johan-hedman-api-1       |       maxTotalSockets: Infinity,
graduation-project-johan-hedman-api-1       |       totalSocketCount: 1,
graduation-project-johan-hedman-api-1       |       [Symbol(kCapture)]: false
graduation-project-johan-hedman-api-1       |     },
graduation-project-johan-hedman-api-1       |     socketPath: undefined,
graduation-project-johan-hedman-api-1       |     method: 'GET',
graduation-project-johan-hedman-api-1       |     maxHeaderSize: undefined,
graduation-project-johan-hedman-api-1       |     insecureHTTPParser: undefined,
graduation-project-johan-hedman-api-1       |     joinDuplicateHeaders: undefined,
graduation-project-johan-hedman-api-1       |     path: '/?apikey=undefined&s=One%20Piece&type=movie',
graduation-project-johan-hedman-api-1       |     _ended: true,
graduation-project-johan-hedman-api-1       |     res: IncomingMessage {
graduation-project-johan-hedman-api-1       |       _readableState: ReadableState {
graduation-project-johan-hedman-api-1       |         objectMode: false,
graduation-project-johan-hedman-api-1       |         highWaterMark: 16384,
graduation-project-johan-hedman-api-1       |         buffer: BufferList { head: null, tail: null, length: 0 },
graduation-project-johan-hedman-api-1       |         length: 0,
graduation-project-johan-hedman-api-1       |         pipes: [],
graduation-project-johan-hedman-api-1       |         flowing: true,
graduation-project-johan-hedman-api-1       |         ended: true,
graduation-project-johan-hedman-api-1       |         endEmitted: true,
graduation-project-johan-hedman-api-1       |         reading: false,
graduation-project-johan-hedman-api-1       |         constructed: true,
graduation-project-johan-hedman-api-1       |         sync: true,
graduation-project-johan-hedman-api-1       |         needReadable: false,
graduation-project-johan-hedman-api-1       |         emittedReadable: false,
graduation-project-johan-hedman-api-1       |         readableListening: false,
graduation-project-johan-hedman-api-1       |         resumeScheduled: false,
graduation-project-johan-hedman-api-1       |         errorEmitted: false,
graduation-project-johan-hedman-api-1       |         emitClose: true,
graduation-project-johan-hedman-api-1       |         autoDestroy: true,
graduation-project-johan-hedman-api-1       |         destroyed: true,
graduation-project-johan-hedman-api-1       |         errored: null,
graduation-project-johan-hedman-api-1       |         closed: true,
graduation-project-johan-hedman-api-1       |         closeEmitted: true,
graduation-project-johan-hedman-api-1       |         defaultEncoding: 'utf8',
graduation-project-johan-hedman-api-1       |         awaitDrainWriters: null,
graduation-project-johan-hedman-api-1       |         multiAwaitDrain: false,
graduation-project-johan-hedman-api-1       |         readingMore: true,
graduation-project-johan-hedman-api-1       |         dataEmitted: true,
graduation-project-johan-hedman-api-1       |         decoder: null,
graduation-project-johan-hedman-api-1       |         encoding: null,
graduation-project-johan-hedman-api-1       |         [Symbol(kPaused)]: false
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       _events: [Object: null prototype] {
graduation-project-johan-hedman-api-1       |         end: [ [Function: responseOnEnd], [Function: handleStreamEnd] ],
graduation-project-johan-hedman-api-1       |         error: [Function: handleStreamError],
graduation-project-johan-hedman-api-1       |         data: [Function: handleStreamData],
graduation-project-johan-hedman-api-1       |         aborted: [Function: handlerStreamAborted]
graduation-project-johan-hedman-api-1       |       },
graduation-project-johan-hedman-api-1       |       _eventsCount: 4,
graduation-project-johan-hedman-api-1       |       _maxListeners: undefined,
graduation-project-johan-hedman-api-1       |       socket: null,
graduation-project-johan-hedman-api-1       |       httpVersionMajor: 1,
graduation-project-johan-hedman-api-1       |       httpVersionMinor: 1,
graduation-project-johan-hedman-api-1       |       httpVersion: '1.1',
graduation-project-johan-hedman-api-1       |       complete: true,
graduation-project-johan-hedman-api-1       |       rawHeaders: [
graduation-project-johan-hedman-api-1       |         'Date',
graduation-project-johan-hedman-api-1       |         'Tue, 05 Sep 2023 06:52:07 GMT',
graduation-project-johan-hedman-api-1       |         'Content-Type',
graduation-project-johan-hedman-api-1       |         'application/json; charset=utf-8',
graduation-project-johan-hedman-api-1       |         'Content-Length',
graduation-project-johan-hedman-api-1       |         '47',
graduation-project-johan-hedman-api-1       |         'Connection',
graduation-project-johan-hedman-api-1       |         'keep-alive',
graduation-project-johan-hedman-api-1       |         'Cache-Control',
graduation-project-johan-hedman-api-1       |         'public, max-age=86400',
graduation-project-johan-hedman-api-1       |         'Expires',
graduation-project-johan-hedman-api-1       |         'Tue, 05 Sep 2023 07:52:07 GMT',
graduation-project-johan-hedman-api-1       |         'Last-Modified',
graduation-project-johan-hedman-api-1       |         'Tue, 05 Sep 2023 06:52:07 GMT',
graduation-project-johan-hedman-api-1       |         'Vary',
graduation-project-johan-hedman-api-1       |         '*, Accept-Encoding',
graduation-project-johan-hedman-api-1       |         'X-AspNet-Version',
graduation-project-johan-hedman-api-1       |         '4.0.30319',
graduation-project-johan-hedman-api-1       |         'X-Powered-By',
graduation-project-johan-hedman-api-1       |         'ASP.NET',
graduation-project-johan-hedman-api-1       |         'Access-Control-Allow-Origin',
graduation-project-johan-hedman-api-1       |         '*',
graduation-project-johan-hedman-api-1       |         'CF-Cache-Status',
graduation-project-johan-hedman-api-1       |         'MISS',
graduation-project-johan-hedman-api-1       |         'Server',
graduation-project-johan-hedman-api-1       |         'cloudflare',
graduation-project-johan-hedman-api-1       |         'CF-RAY',
graduation-project-johan-hedman-api-1       |         '801c8c329a890e28-AMS'
graduation-project-johan-hedman-api-1       |       ],
graduation-project-johan-hedman-api-1       |       rawTrailers: [],
graduation-project-johan-hedman-api-1       |       joinDuplicateHeaders: undefined,
graduation-project-johan-hedman-api-1       |       aborted: false,
graduation-project-johan-hedman-api-1       |       upgrade: false,
graduation-project-johan-hedman-mongo-1     | {"t":{"$date":"2023-09-05T06:52:07.576+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn1","msg":"Interrupted operation as its client disconnected","attr":{"opId":11367}}
```

Reproducer:

1. Start a new codespace
2. Configure .env files in front- and backend
3. docker-compose up
4. Sign up successfully
5. Login 
6. Search for a movie
7. Kaboooom

**Comment by echo75** [comment]
Yes, the API-key for OMDb is missing in your configuration.
This is a setup issue. But what happens when the numbers of calls should exceed. 
I have to fix it.
